-----------------------------------------------------------------------------------------------
--Students:
--Meylin Carvajal Baltodano
--Luis D. Rivas Castro
--Ma. Fernanda Vega Acosta

-----------------------------------------------------------------------------------------------

--All the sequences that are going to be used for the  id s in the inserts for each table
CREATE SEQUENCE sAdopterRating
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sAdoption
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sAdoptionAppication
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sAdoptionPhoto
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sAssociation
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sBlackistReport
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sBreed
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sCanton
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sColor
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sCurrency
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sDisease
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sDistrict
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sDonation
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sDonationAllLocation
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sEmail
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sFosterCondition
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sHealthStatus
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sJournal
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sMatch
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sMedicine
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sPerson
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sPet
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sPetContact
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sPetPhoto
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sPetStatus
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sPetSize
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sPetType
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sPhone
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sProvince
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sRequiresFoodDonation
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sRescuer
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sReward
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sStarRating
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sSysParameter
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sTrainingEase
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sTreatment
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;

CREATE SEQUENCE sVeterinarian
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 5000
NOCACHE
NOCYCLE;
